on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Deploy to s3 staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1
      - run: yarn
      - run: yarn deploy
