on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Deploy to s3 production
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: yarn
      - run: yarn build-deploy-prod
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_INDEX: 'Docs'
          SEGMENT_KEY: 'RUtph5AIOikMUv9vQUVqHrb6G2pALs0T'
          AWS_S3_BUCKET: 'launchdarkly-docs-production'
          AWS_HOSTNAME: 'docs-prod.launchdarkly.com'

  cypress-run:
    runs-on: ubuntu-latest
    name: Run cypress
    needs: [build-deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
      - run: echo ::set-env name=SLACK_MESSAGE::$(echo "{\\\"channel\\\":\\\"CPM7ALZC2\\\",\\\"text\\\":\\\"<https://github.com/launchdarkly/git-gatsby/actions/runs/$GITHUB_RUN_ID|Cypress> failed for <https://github.com/launchdarkly/git-gatsby/commit/$GITHUB_SHA|$GITHUB_SHA>.\\\"}")
      - name: Notify slack
        if: failure()
        uses: pullreminders/slack-action@master
        with:
          args: ${{ env.SLACK_MESSAGE }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.CYPRESS_SLACK_BOT_TOKEN }}
